# Generated by Django 3.0.2 on 2020-01-20 18:21

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', markdownx.models.MarkdownxField()),
                ('pub_datetime', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=400)),
                ('projectgraphic', models.ImageField(upload_to='gallery')),
                ('link', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
