# Generated by Django 2.2.6 on 2019-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='link',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
